### ISSUE TITLE
Choose which language..

### ISSUE THREAD

**Issue by pommedefrance** [jelmervdl/translatelocally-web-ext#56]
hi, difficult for me to speak english ;-)
is it possible that this addon detect the language of the page ? i've have always czech-english..and i have to choose english-french..is it normal ?
or choose one time for all english-french (for me ;-) ) ?
thks, i hope it's understandable :-(

**Comment by jelmervdl** [comment]
Hi @pommedefrance

It should by default prefer the languages you configured in your browser. Do you have French selected as your preferred web page language? 
<img width="901" alt="image" src="https://user-images.githubusercontent.com/198639/201875482-27eb0a3c-c114-44b2-a89d-5a9b831f50e1.png">

I recently added a feature where if you do select something else as the target language, it should now remember this. Regardless of your preferred web page language setting. It isn't in the released version yet, but I'll push a new release in the coming days.

**Comment by pommedefrance** [comment]
yeah, it's working :-) ! thks
but for privacy, i prefer let in english..with the next release, perhaps i can choose a "fix" translate..
